# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Usacloud < Formula
  desc ""
  homepage "https://github.com/sacloud/usacloud"
  version "1.20.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sacloud/usacloud/releases/download/v1.20.1/usacloud_darwin-amd64.zip"
      sha256 "5baf419e19832dccbe09e3e3a19963deba3301d786f7c3cc11cc7207f9e496cc"

      def install
        bin.install "usacloud"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sacloud/usacloud/releases/download/v1.20.1/usacloud_darwin-arm64.zip"
      sha256 "6544d3aba10a58bdc73709c22aae717c09773680b95d90699262de0161cf3a92"

      def install
        bin.install "usacloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sacloud/usacloud/releases/download/v1.20.1/usacloud_linux-amd64.zip"
      sha256 "f651d16663d904db7bfd8815a9b1b00a896764804fc0a6865a2f33b315bc5a1b"
      def install
        bin.install "usacloud"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sacloud/usacloud/releases/download/v1.20.1/usacloud_linux-arm.zip"
      sha256 "24aa148c87051d00896036e7116f6f05d56cabd09087f7567a0d19293147f8f2"
      def install
        bin.install "usacloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sacloud/usacloud/releases/download/v1.20.1/usacloud_linux-arm64.zip"
      sha256 "d699772b4ea6f8477e253d77c9a9c9b40ecc3994d71926a812edece3f3d34694"
      def install
        bin.install "usacloud"
      end
    end
  end

  test do
    system "#{bin}/usacloud --version"
  end
end
